import React, { useContext, useEffect } from 'react'
import { Page } from '../../components/Page'
import { MovieListsContext } from '../../store/MovieListsContext'
import { ShowCarousel } from '../../components/ShowCarousel'

export function Movies(): JSX.Element {
  const {
    action,
    adventure,
    animation,
    comedy,
    crime,
    documentary,
    drama,
    fantasy,
    family,
    history,
    horror,
    mistery,
    music,
    romance,
    scienceFiction,
    thriller,
    war,
    western,
    isLoadingAction,
    isLoadingAdventure,
    isLoadingAnimation,
    isLoadingComedy,
    isLoadingCrime,
    isLoadingDocumentary,
    isLoadingDrama,
    isLoadingFantasy,
    isLoadingFamily,
    isLoadingHistory,
    isLoadingHorror,
    isLoadingMistery,
    isLoadingMusic,
    isLoadingRomance,
    isLoadingScienceFiction,
    isLoadingThriller,
    isLoadingWar,
    isLoadingWestern,
    fetchAction,
    fetchAdventure,
    fetchAnimation,
    fetchComedy,
    fetchCrime,
    fetchDocumentary,
    fetchDrama,
    fetchFantasy,
    fetchFamily,
    fetchHistory,
    fetchHorror,
    fetchMistery,
    fetchMusic,
    fetchRomance,
    fetchScienceFiction,
    fetchThriller,
    fetchWar,
    fetchWestern,
  } = useContext(MovieListsContext)

  useEffect(() => {
    fetchAction()
    fetchAdventure()
    fetchAnimation()
    fetchComedy()
    fetchCrime()
    fetchDocumentary()
    fetchDrama()
    fetchFantasy()
    fetchFamily()
    fetchHistory()
    fetchHorror()
    fetchMistery()
    fetchMusic()
    fetchRomance()
    fetchScienceFiction()
    fetchThriller()
    fetchWar()
    fetchWestern()
  }, [])

  return (
    <Page>
      <ShowCarousel
        title="Action"
        shows={action}
        isLoading={isLoadingAction}
        data-testid="carousel-action"
      />
      <ShowCarousel
        title="Adventure"
        shows={adventure}
        isLoading={isLoadingAdventure}
        data-testid="carousel-adventure"
      />
      <ShowCarousel
        title="Animation"
        shows={animation}
        isLoading={isLoadingAnimation}
        data-testid="carousel-animation"
      />
      <ShowCarousel
        title="Comedy"
        shows={comedy}
        isLoading={isLoadingComedy}
        data-testid="carousel-comedy"
      />
      <ShowCarousel
        title="Crime"
        shows={crime}
        isLoading={isLoadingCrime}
        data-testid="carousel-crime"
      />
      <ShowCarousel
        title="Documentary"
        shows={documentary}
        isLoading={isLoadingDocumentary}
        data-testid="carousel-documentary"
      />
      <ShowCarousel
        title="Drama"
        shows={drama}
        isLoading={isLoadingDrama}
        data-testid="carousel-drama"
      />
      <ShowCarousel
        title="Family"
        shows={family}
        isLoading={isLoadingFamily}
        data-testid="carousel-family"
      />
      <ShowCarousel
        title="Fantasy"
        shows={fantasy}
        isLoading={isLoadingFantasy}
        data-testid="carousel-fantasy"
      />
      <ShowCarousel
        title="History"
        shows={history}
        isLoading={isLoadingHistory}
        data-testid="carousel-history"
      />
      <ShowCarousel
        title="Horror"
        shows={horror}
        isLoading={isLoadingHorror}
        data-testid="carousel-horror"
      />
      <ShowCarousel
        title="Music"
        shows={music}
        isLoading={isLoadingMusic}
        data-testid="carousel-music"
      />
      <ShowCarousel
        title="Mistery"
        shows={mistery}
        isLoading={isLoadingMistery}
        data-testid="carousel-mistery"
      />
      <ShowCarousel
        title="Romance"
        shows={romance}
        isLoading={isLoadingRomance}
        data-testid="carousel-romance"
      />
      <ShowCarousel
        title="Science fiction"
        shows={scienceFiction}
        isLoading={isLoadingScienceFiction}
        data-testid="carousel-science-fiction"
      />
      <ShowCarousel
        title="Thriller"
        shows={thriller}
        isLoading={isLoadingThriller}
        data-testid="carousel-thriller"
      />
      <ShowCarousel
        title="War"
        shows={war}
        isLoading={isLoadingWar}
        data-testid="carousel-war"
      />
      <ShowCarousel
        title="Western"
        shows={western}
        isLoading={isLoadingWestern}
        data-testid="carousel-western"
      />
    </Page>
  )
}
