import { MovieListsState } from './types'

export const initialState: MovieListsState = {
  trending: [],
  inTheatres: [],
  similar: [],
  recommended: [],
  mostPopular: [],
  bestComedies: [],
  topRatedDocumentaries: [],
  scifiAndFantasy: [],
  family: [],
  listsByGenres: [],
  category: {
    data: [],
    page: 0,
    pages: 0,
  },

  isLoadingTrending: false,
  isLoadingInTheatres: false,
  isLoadingSimilar: false,
  isLoadingRecommended: false,
  isLoadingMostPopular: false,
  isLoadingBestComedies: false,
  isLoadingScifiAndFantasy: false,
  isLoadingFamily: false,
  isLoadingTopRatedDocumentaries: false,
  isLoadingListsByGenres: false,
  isLoadingByCategory: false,
  hasCategoryErrors: false,

  fetchTrending: () => null,
  fetchSimilar: () => null,
  fetchRecommended: () => null,
  fetchMostPopular: () => null,
  fetchBestComedies: () => null,
  fetchScifiAndFantasy: () => null,
  fetchFamily: () => null,
  fetchTopRatedDocumentaries: () => null,
  fetchInTheatres: () => null,
  fetchListCategory: () => null,
  fetchListsByGenres: () => null,
}
