name: "Lint / Build / Test"
on:
  push:
    branches-ignore:
      - main
jobs:
  Lint-Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: yarn install

      - name: Lint Project
        run: yarn run lint:check

      - name: Build Project
        run: yarn run build

      - name: Test Project
        run: yarn run test
